name: "Backporting GitHub Action"
description: "GitHub action providing an automated way to backport pull requests from one branch to another"
inputs:
  dry-run:
    description: "If enabled the tool does not create any pull request nor push anything remotely."
    required: false
    default: "false"
  auth:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)."
    default: ${{ github.token }}
    required: false
  pull-request:
    description: "URL of the pull request to backport, e.g., https://github.com/lampajr/backporting/pull/1."
    required: true
  target-branch:
    description: "Branch where the pull request must be backported to."
    required: true

runs:
  using: node16
  main: dist/gha/index.js

branding:
  icon: 'git-merge'
  color: 'blue'